### Site Settings ###
title               : BornToBeRoot
description         : >-
                      Network and system administrator who prefers to define infrastructure as code.<br />
                      Maintainer of <a href="https://borntoberoot.net/NETworkManager">NETworkManager</a>.
baseurl             : ""
repository          : BornToBeRoot/borntoberoot.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md  


### Author Info ###
author:
  name              : BornToBeRoot
  image             : images/borntoberoot.png
#  email             : username@domain.com
  github            : BornToBeRoot
  twitter           : _BornToBeRoot


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
